- name: EzyAdmin ntpinstallcentos7
  hosts: all
  tasks:
  - name: Hostname a variable
    debug: var=inventory_hostname

  - name: Install ntp ntpstat
    command: yum install ntp -y
    become: True
    
  - name: Enable ntp
    shell: systemctl enable ntpd
    become: True
    
  - name: Move file original
    shell: mv /etc/ntp.conf /etc/ntp.conf.original
    become: True
    
  - name: new the ntp.conf
    copy:
     src: ntp.conf
     dest: /etc/
     owner: root
     group: root
     mode: 0644
    become: True
    
  - name: Restart ntp for sync
    command: systemctl start ntpd.service
    become: True

  - name: Sync Time ntp
    command: ntpstat
    ignore_errors: true
    become: True
    
  - name: Check Sum
    command: ntpq -p
    become: True