- name: EzyAdmin ntpinstallcentos7
  hosts: all
  tasks:
  - name: Hostname a variable
    debug: var=inventory_hostname
    
---
- debug: var=list

- name: Main process for linux check os version for centos5
  block:
    -name: install ntp centos5
     include: ntpinstallcentos6.yaml
     loop: "{{ list }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'
  
- name: Main process for linux check os version for centos6
  block:
    -name: install ntp centos6
     include: ntpinstallcentos6.yaml
     loop: "{{ list }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'
  
- name: Main process for linux check os version for centos6
  block:
    -name: install ntp centos7
     include: ntpinstallcentos7.yaml
     loop: "{{ list }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- name: Main process for linux check os version for centos6
  block:
    -name: install ntp Ubuntu
     include: ntpinstalldb.yaml
     loop: "{{ list }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == 'Ubuntu'
  
  - name: Main process for linux check os version for centos6
  block:
    -name: install ntp Debian
     include: ntpinstalldb.yaml
     loop: "{{ list }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == 'Debian'
  
  
  
